"""Report service - generates HTML and PDF reports."""

from __future__ import annotations

import io
from datetime import datetime
from typing import Optional

from core.logging_config import get_logger
from models.evaluation_result import EvaluationResult, QuestionEvaluation

logger = get_logger(__name__)


class ReportService:
    """Generates evaluation reports in HTML and PDF formats."""

    def generate_html_report(self, result: EvaluationResult, subject: str = "", strictness: int = 6) -> str:
        """Generate complete HTML evaluation report."""
        questions_html = ""
        for qe in result.question_evaluations:
            questions_html += self._render_question_section(qe)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>UPSC Evaluation Report</title>
<style>
body {{ font-family: 'Segoe UI', Tahoma, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; color: #333; }}
.container {{ max-width: 900px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 2px 20px rgba(0,0,0,0.1); }}
.header {{ text-align: center; border-bottom: 3px solid #4a90d9; padding-bottom: 20px; margin-bottom: 30px; }}
.header h1 {{ color: #2c3e50; margin: 0 0 8px 0; font-size: 28px; }}
.header p {{ color: #666; margin: 0; }}
.summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }}
.stat-card {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; }}
.stat-card.secondary {{ background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }}
.stat-card.tertiary {{ background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); }}
.stat-card h3 {{ margin: 0 0 4px 0; font-size: 14px; opacity: 0.9; }}
.stat-card .value {{ font-size: 32px; font-weight: bold; }}
.question-card {{ border: 1px solid #e0e0e0; border-radius: 10px; padding: 24px; margin: 20px 0; }}
.question-card h3 {{ color: #4a90d9; margin-top: 0; }}
.score-badge {{ display: inline-block; padding: 6px 16px; background: #4a90d9; color: white; border-radius: 20px; font-weight: bold; }}
.rubric-table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
.rubric-table th, .rubric-table td {{ padding: 10px 14px; border-bottom: 1px solid #eee; text-align: left; }}
.rubric-table th {{ background: #f8f9fa; font-weight: 600; }}
.missing {{ background: #fff3cd; padding: 12px 16px; border-radius: 8px; margin: 8px 0; border-left: 4px solid #ffc107; }}
.feedback {{ background: #e8f5e9; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #4caf50; }}
.model-answer {{ background: #f3e5f5; padding: 16px; border-radius: 8px; margin: 16px 0; border-left: 4px solid #9c27b0; }}
.strengths {{ color: #2e7d32; }}
.weaknesses {{ color: #c62828; }}
.footer {{ text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>UPSC Answer Evaluation Report</h1>
        <p>Subject: {subject} | Strictness: {strictness}/10 | Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}</p>
    </div>

    <div class="summary-grid">
        <div class="stat-card">
            <h3>Total Score</h3>
            <div class="value">{result.total_marks_awarded}/{result.total_marks_possible}</div>
        </div>
        <div class="stat-card secondary">
            <h3>Percentage</h3>
            <div class="value">{result.overall_percentage:.1f}%</div>
        </div>
        <div class="stat-card tertiary">
            <h3>Questions</h3>
            <div class="value">{len(result.question_evaluations)}</div>
        </div>
    </div>

    <h2>Question-wise Analysis</h2>
    {questions_html}

    <div class="footer">
        Generated by UPSC Answer Evaluator | AI-powered evaluation system
    </div>
</div>
</body>
</html>"""
        return html

    def generate_pdf_bytes(self, result: EvaluationResult, subject: str = "", strictness: int = 6) -> bytes:
        """Generate PDF report as bytes for download."""
        html = self.generate_html_report(result, subject, strictness)
        try:
            from weasyprint import HTML
            pdf_bytes = HTML(string=html).write_pdf()
            return pdf_bytes
        except ImportError:
            return self._fallback_pdf(result)

    def _fallback_pdf(self, result: EvaluationResult) -> bytes:
        """Fallback PDF generation using basic text."""
        content = f"UPSC Evaluation Report\n{'='*50}\n\n"
        content += f"Total Score: {result.total_marks_awarded}/{result.total_marks_possible}\n"
        content += f"Percentage: {result.overall_percentage:.1f}%\n\n"

        for qe in result.question_evaluations:
            content += f"\nQ{qe.question_number} ({qe.max_marks} marks) - Awarded: {qe.awarded_marks}\n"
            content += f"{'─'*40}\n"
            if qe.strengths:
                content += f"Strengths: {', '.join(qe.strengths[:3])}\n"
            if qe.weaknesses:
                content += f"Weaknesses: {', '.join(qe.weaknesses[:3])}\n"

        return content.encode("utf-8")

    def _render_question_section(self, qe: QuestionEvaluation) -> str:
        """Render a single question's evaluation as HTML."""
        rubric_rows = ""
        for rs in qe.rubric_scores:
            pct = (rs.score / rs.max_score * 100) if rs.max_score > 0 else 0
            rubric_rows += f"<tr><td>{rs.component.replace('_', ' ').title()}</td><td>{rs.score:.1f}/{rs.max_score:.1f}</td><td>{pct:.0f}%</td></tr>"

        missing_html = ""
        for item in qe.missing_content[:5]:
            missing_html += f'<div class="missing">{item}</div>'

        strengths_html = "".join(f"<li>{s}</li>" for s in qe.strengths[:4])
        weaknesses_html = "".join(f"<li>{w}</li>" for w in qe.weaknesses[:4])

        return f"""
    <div class="question-card">
        <h3>Question {qe.question_number} <span class="score-badge">{qe.awarded_marks}/{qe.max_marks}</span></h3>

        <table class="rubric-table">
            <tr><th>Component</th><th>Score</th><th>%</th></tr>
            {rubric_rows}
        </table>

        {"<h4 class='strengths'>Strengths</h4><ul>" + strengths_html + "</ul>" if strengths_html else ""}
        {"<h4 class='weaknesses'>Weaknesses</h4><ul>" + weaknesses_html + "</ul>" if weaknesses_html else ""}

        {"<h4>Missing Content</h4>" + missing_html if missing_html else ""}

        {"<div class='feedback'><strong>Examiner Feedback:</strong> " + qe.upsc_style_feedback + "</div>" if qe.upsc_style_feedback else ""}

        {"<div class='model-answer'><strong>Model Answer:</strong><br>" + qe.model_answer[:800] + "...</div>" if qe.model_answer else ""}
    </div>"""
